# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biopb/ome/filter.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'biopb/ome/filter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from biopb.ome import manufacturer_spec_pb2 as biopb_dot_ome_dot_manufacturer__spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62iopb/ome/filter.proto\x12\tbiopb.ome\x1a!biopb/ome/manufacturer_spec.proto\"\xd8\x02\n\x12TransmittanceRange\x12\x13\n\x06\x63ut_in\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x13\n\x0b\x63ut_in_unit\x18\x03 \x01(\t\x12\x14\n\x07\x63ut_out\x18\x04 \x01(\x02H\x01\x88\x01\x01\x12\x14\n\x0c\x63ut_out_unit\x18\x05 \x01(\t\x12\x1d\n\x10\x63ut_in_tolerance\x18\x06 \x01(\x02H\x02\x88\x01\x01\x12\x1d\n\x15\x63ut_in_tolerance_unit\x18\x07 \x01(\t\x12\x1e\n\x11\x63ut_out_tolerance\x18\x08 \x01(\x02H\x03\x88\x01\x01\x12\x1e\n\x16\x63ut_out_tolerance_unit\x18\t \x01(\t\x12\x1a\n\rtransmittance\x18\n \x01(\x02H\x04\x88\x01\x01\x42\t\n\x07_cut_inB\n\n\x08_cut_outB\x13\n\x11_cut_in_toleranceB\x14\n\x12_cut_out_toleranceB\x10\n\x0e_transmittance\"\xde\x02\n\x06\x46ilter\x12\x36\n\x11manufacturer_spec\x18\x02 \x01(\x0b\x32\x1b.biopb.ome.ManufacturerSpec\x12$\n\x04type\x18\x03 \x01(\x0e\x32\x16.biopb.ome.Filter.Type\x12:\n\x13transmittence_range\x18\x04 \x01(\x0b\x32\x1d.biopb.ome.TransmittanceRange\x12\x14\n\x0c\x66ilter_wheel\x18\x05 \x01(\t\x12\x16\n\x0e\x61nnotation_ids\x18\x06 \x03(\t\"\x8b\x01\n\x04Type\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0c\n\x08\x44ICHROIC\x10\x01\x12\x0c\n\x08LONGPASS\x10\x02\x12\r\n\tSHORTPASS\x10\x03\x12\x0c\n\x08\x42\x41NDPASS\x10\x04\x12\r\n\tMULTIPASS\x10\x05\x12\x12\n\x0eNEUTRALDENSITY\x10\x06\x12\x0b\n\x07TUNABLE\x10\x07\x12\t\n\x05OTHER\x10\x08\"Z\n\x08\x44ichroic\x12\x36\n\x11manufacturer_spec\x18\x02 \x01(\x0b\x32\x1b.biopb.ome.ManufacturerSpec\x12\x16\n\x0e\x61nnotation_ids\x18\x06 \x03(\tB\r\n\tbiopb.omeP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biopb.ome.filter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tbiopb.omeP\001'
  _globals['_TRANSMITTANCERANGE']._serialized_start=73
  _globals['_TRANSMITTANCERANGE']._serialized_end=417
  _globals['_FILTER']._serialized_start=420
  _globals['_FILTER']._serialized_end=770
  _globals['_FILTER_TYPE']._serialized_start=631
  _globals['_FILTER_TYPE']._serialized_end=770
  _globals['_DICHROIC']._serialized_start=772
  _globals['_DICHROIC']._serialized_end=862
# @@protoc_insertion_point(module_scope)
