# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biopb/ome/light_source_setting.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'biopb/ome/light_source_setting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$biopb/ome/light_source_setting.proto\x12\tbiopb.ome\"\x98\x01\n\x12LightSourceSetting\x12\x17\n\x0flight_source_id\x18\x01 \x01(\t\x12\x18\n\x0b\x61ttenuation\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x17\n\nwavelength\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x17\n\x0fwavelength_unit\x18\x04 \x01(\tB\x0e\n\x0c_attenuationB\r\n\x0b_wavelengthB\r\n\tbiopb.omeP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biopb.ome.light_source_setting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tbiopb.omeP\001'
  _globals['_LIGHTSOURCESETTING']._serialized_start=52
  _globals['_LIGHTSOURCESETTING']._serialized_end=204
# @@protoc_insertion_point(module_scope)
