# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biopb/ome/project.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'biopb/ome/project.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62iopb/ome/project.proto\x12\tbiopb.ome\"\x90\x01\n\x07Project\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ndescrption\x18\x03 \x01(\t\x12\x17\n\x0f\x65xperimenter_id\x18\x04 \x01(\t\x12\x1d\n\x15\x65xperimenter_group_id\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x61taset_ids\x18\x06 \x03(\t\x12\x16\n\x0e\x61nnotation_ids\x18\x07 \x03(\tB\r\n\tbiopb.omeP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biopb.ome.project_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tbiopb.omeP\001'
  _globals['_PROJECT']._serialized_start=39
  _globals['_PROJECT']._serialized_end=183
# @@protoc_insertion_point(module_scope)
